# Terraform Configuration generated by ArchGen AI
# Target Provider: Azure (azurerm)

terraform {
  required_version = ">= 1.3.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }
}

provider "azurerm" {
  features {}
}

# Unique suffix for strict Azure global naming
resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

# Core Resource Group for scoping deployment
resource "azurerm_resource_group" "rg" {
  name     = "rg-${var.project_name}-${var.environment}"
  location = var.location
}

# ==========================================
# SHARED INFRASTRUCTURE (Defined Once)
# ==========================================
# Container App Environment for all Backend Microservices
resource "azurerm_container_app_environment" "app_env" {
  name                = "cae-${var.project_name}-${var.environment}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-${var.project_name}-${var.environment}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  address_space       = ["10.0.0.0/16"]
}

# ==========================================
# SERVICE: Secure Virtual Network (VPC/VNet) (NetworkGroupNode)
# ==========================================

# ==========================================
# SERVICE: Azure Front Door & WAF Ingress (GatewayNode)
# ==========================================
# Network and IP Resources for Gateway Ingress
resource "azurerm_public_ip" "gw_pip_gatewaynod" {
  name                = "pip-${substr(var.project_name, 0, 8)}-gw-${substr(var.environment, 0, 4)}-gatewaynod"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_subnet" "gw_subnet_gatewaynod" {
  name                 = "snet-gw-gatewaynod"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.1.0/24"]
}


# ==========================================
# SERVICE: Azure CDN (Edge Content Delivery) (GatewayNode)
# ==========================================
# Network and IP Resources for Gateway Ingress
resource "azurerm_public_ip" "gw_pip_cdnnode" {
  name                = "pip-${substr(var.project_name, 0, 8)}-gw-${substr(var.environment, 0, 4)}-cdnnode"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_subnet" "gw_subnet_cdnnode" {
  name                 = "snet-gw-cdnnode"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.1.0/24"]
}


# ==========================================
# SERVICE: Azure Static Web App (SPA) (FrontendNode)
# ==========================================
# static Web App for SPA hosting (React/Vue/Next.js)
resource "azurerm_static_web_app" "spa_frontend_frontendno" {
  name                = "stt-${substr(var.project_name, 0, 8)}-fe-${substr(var.environment, 0, 4)}-frontendno"
  resource_group_name = azurerm_resource_group.rg.name
  location            = "eastus2" # Azure Static Web Apps requires specific global hubs
}


# ==========================================
# SERVICE: Azure Container App (BackendNode)
# ==========================================
# Container App Compute
resource "azurerm_container_app" "api_backend_backendnod" {
  name                         = "ca-${substr(var.project_name, 0, 8)}-be-${substr(var.environment, 0, 4)}-backendnod"
  container_app_environment_id = azurerm_container_app_environment.app_env.id
  resource_group_name          = azurerm_resource_group.rg.name
  revision_mode                = "Single"

  template {
    container {
      name   = "api-service"
      image  = "mcr.microsoft.com/azuredocs/aci-helloworld:latest"
      cpu    = "0.25"
      memory = "0.5Gi"
      
      env {
        name  = "ENVIRONMENT"
        value = var.environment
      }

      # Dynamic Environment Bindings based on visual edge connections!
      env {
        name  = "DATABASE_URL"
        value = "postgresql://dbadmin:${var.db_password}@psql-${substr(var.project_name, 0, 8)}-db-${substr(var.environment, 0, 4)}-databaseno.postgres.database.azure.com/appdb"
      }
      env {
        name  = "REDIS_HOST"
        value = "redis-${substr(var.project_name, 0, 8)}-cache-${substr(var.environment, 0, 4)}-cachenode.redis.cache.windows.net"
      }
      env {
        name  = "KEYVAULT_ENDPOINT"
        value = "https://kv-${substr(var.project_name, 0, 8)}-${substr(var.environment, 0, 4)}-vaultnode.vault.azure.net/"
      }
    }
  }

  ingress {
    external_enabled = true
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}


# ==========================================
# SERVICE: Azure Service Bus / Event Grid (BackendNode)
# ==========================================
# Container App Compute
resource "azurerm_container_app" "api_backend_queuenode" {
  name                         = "ca-${substr(var.project_name, 0, 8)}-be-${substr(var.environment, 0, 4)}-queuenode"
  container_app_environment_id = azurerm_container_app_environment.app_env.id
  resource_group_name          = azurerm_resource_group.rg.name
  revision_mode                = "Single"

  template {
    container {
      name   = "api-service"
      image  = "mcr.microsoft.com/azuredocs/aci-helloworld:latest"
      cpu    = "0.25"
      memory = "0.5Gi"
      
      env {
        name  = "ENVIRONMENT"
        value = var.environment
      }

      # Dynamic Environment Bindings based on visual edge connections!
    }
  }

  ingress {
    external_enabled = true
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}


# ==========================================
# SERVICE: Azure DDoS Protection Plan (SecurityNode)
# ==========================================
# DDoS Protection Plan for volumetric attack mitigation
resource "azurerm_network_ddos_protection_plan" "ddos_ddosnode" {
  name                = "ddos-${substr(var.project_name, 0, 8)}-${substr(var.environment, 0, 4)}-ddosnode"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

# ==========================================
# SERVICE: Azure Key Vault (HSM Secrets) (SecurityNode)
# ==========================================
# Key Vault for system secret generation and certificate storage
resource "azurerm_key_vault" "key_vault_vaultnode" {
  name                        = "kv-${substr(var.project_name, 0, 6)}-${substr(var.environment, 0, 3)}-vaultnode"
  location                    = azurerm_resource_group.rg.location
  resource_group_name         = azurerm_resource_group.rg.name
  enabled_for_disk_encryption = true
  tenant_id                   = "00000000-0000-0000-0000-000000000000" # Placeholder UUID for configuration
  sku_name                    = "standard"
}

# ==========================================
# SERVICE: Azure Cache for Redis (HA) (CacheNode)
# ==========================================
# Redis Cache for quick session states and transient database caching
resource "azurerm_redis_cache" "redis_cache_cachenode" {
  name                = "redis-${substr(var.project_name, 0, 8)}-cache-${substr(var.environment, 0, 4)}-cachenode"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  capacity            = 1
  family              = "C"
  sku_name            = "Standard"
  non_ssl_port_enabled = false
  minimum_tls_version = "1.2"
}


# ==========================================
# SERVICE: Azure Cosmos DB (NoSQL) (DatabaseNode)
# ==========================================
# Cosmos DB Account for NoSQL document storage
resource "azurerm_cosmosdb_account" "cosmos_db_databaseno" {
  name                = "cosmos-${substr(var.project_name, 0, 8)}-db-${substr(var.environment, 0, 4)}-databaseno"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  consistency_policy {
    consistency_level = "Session"
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}


# ==========================================
# SERVICE: Azure Storage Account (Hot Blobs) (StorageNode)
# ==========================================
# General Purpose Block Storage for documents and binary files
resource "azurerm_storage_account" "blob_storage_storagenod" {
  name                     = lower("st${substr(var.project_name, 0, 6)}${substr(var.environment, 0, 3)}${random_string.suffix.result}storagenod")
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "upload_bucket_storagenod" {
  name                  = "media"
  storage_account_name  = azurerm_storage_account.blob_storage_storagenod.name
  container_access_type = "blob"
}


# ==========================================
# SERVICE: Azure Log Analytics & App Insights (MonitoringNode)
# ==========================================

